Add missing dependency to stream.deferred
clj-commons/manifold pull request #174
Opened 2019-06-09 12:15 UTC by SevereOverfl0w

This namespace cannot be `require`d without adding this dependency

2021-03-13 23:13 UTC, KingMob commented
Confirmed. Both `def-sink` and `def-source` refer to manifold.stream.graph, but it's not required.

2021-03-13 23:15 UTC, KingMob requested changes

2021-03-13 23:15 UTC, KingMob commented on src/manifold/stream/deferred.clj
> +    manifold.stream.graph))
@SevereOverfl0w There's an extra paren here.

2021-03-20 09:45 UTC, SevereOverfl0w commented on src/manifold/stream/deferred.clj
> +    manifold.stream.graph))
Fixed! :)

2021-03-25 20:02 UTC, KingMob approved these changes

2021-07-04 18:16 UTC, merged