Upgrade to core.async 1.6.673
clj-commons/manifold pull request #231
Opened 2023-04-05 16:24 UTC by tanzoniteblack

Some of the functions that we were relying on to hijack the go state machine compilation changed namespaces. This updates the code to reference where they now live.

Addresses https://github.com/clj-commons/manifold/issues/229

2023-04-06 03:44 UTC, KingMob requested changes
Wow, that was fast!

Unfortunately, since not everyone uses core.async with manifold, it's declared `scope :provided`, which means they choose which version to bring. (And even without scope provided, users could always override the core.async dep.)

The solution needs to check both namespaces where the vars could be defined, and then use the one it finds.

2023-04-17 14:55 UTC, tanzoniteblack commented
Sorry for the slow response here, @KingMob . I've been thinking this over and I'm not sure that the complications of implementation make it worth supporting both. I think having a minimum version pinned as our provided scope, and warning in the release that if you upgrade to this version there's a particular minimum version you're expected to have of core.async. At least, my interpretation of provided dependencies has always been, "We tested with this particular version of the library. Caveat emptor if you choose to use a different version."

Let me know your thoughts?

2023-04-18 07:20 UTC, KingMob commented
Hmmm. I guess my problem with "Caveat emptor if you choose to use a different version" is that usually means "We haven't tested with your version, and we can't predict what will happen". But in this case, we know it will break, and we know how to fix it. It feels like we're punting a problem to the user. OTOH, a quick Github search doesn't show anyone using it, so... ¯\\\_(ツ)\_/¯

I think, to be safe, I'd still rather support both namespaces.

2023-05-10 22:04 UTC, tanzoniteblack commented
@KingMob , I've validated locally that the change I made works with both the current & older version of core.async, but I'm unsure the best way to set up circleci to actually test both

2023-05-11 02:52 UTC, KingMob commented
Great work! 

To test both, maybe add two extra profiles in project.clj? One `:old-core-async` and one `:new-core-async` with the right deps. Then run both like:

```
lein with-profiles +old-core-async test :only whatever.the.go-off-tests.namespace.is
lein with-profiles +new-core-async test :only whatever.the.go-off-tests.namespace.is
```

I think that would work

2023-05-11 20:49 UTC, tanzoniteblack commented
@KingMob , I added a new profile explicitly for the old core.async version and have the default deps list using the newer version, rather than adding profiles for both. Circleci config has also been updated to run the go-off tests. I've verified locally that the different profiles are correctly using the right core.async versions.

2023-05-12 02:59 UTC, KingMob approved these changes
LGTM

2023-05-12 02:59 UTC, KingMob commented
Fixes #229

2023-05-12 03:00 UTC, merged